Upgrade to 2.4.0
YunoHost-Apps/peertube_ynh pull request #186
Opened 2020-09-30 20:47 UTC by yalh76

## Problem
- *New version upstream*

## Solution
- *Upgrade to V.2.4.0*
- *Small typos*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/peertube_ynh%20PR183%20(yalh76)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/peertube_ynh%20PR183%20(yalh76)/)

2020-10-01 19:44 UTC, ericgaspar requested changes

2020-10-01 19:44 UTC, ericgaspar commented on README_fr.md
> +[![Integration level](https://dash.yunohost.org/integration/peertube.svg)](https://dash.yunohost.org/appci/app/peertube) ![](https://ci-apps.yunohost.org/ci/badges/peertube.status.svg) ![](https://ci
```suggestion
[![Niveau d'intégration](https://dash.yunohost.org/integration/peertube.svg)](https://dash.yunohost.org/appci/app/peertube) ![](https://ci-apps.yunohost.org/ci/badges/peertube.status.svg) ![](https://ci-apps.yunohost.org/ci/badges/peertube.maintain.svg)  
```

2020-10-16 17:47 UTC, yalh76 commented
PR is ready to be merged :)

2020-10-16 17:51 UTC, ericgaspar approved these changes

2020-10-16 22:22 UTC, merged