Change binary name to yt-dlp
YunoHost-Apps/peertube_ynh pull request #342
Opened 2022-09-17 17:25 UTC by tituspijean

Attempt to fix #340. Works on a test instance with public videos (but did not work on YunoHost Cinema, though).

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-09-17 17:27 UTC, tituspijean commented
We should update the upgrade script to patch `production.yaml` though.

2022-09-17 18:18 UTC, fflorent requested changes

2022-09-17 18:18 UTC, fflorent commented on conf/production.yaml
>          url: 'https://yt-dl.org/downloads/latest/youtube-dl'
The URL need to be changed for yt-dlp:

https://api.github.com/repos/yt-dlp/yt-dlp/releases

2022-09-18 16:28 UTC, fflorent approved these changes
Thanks @tituspijean, LGTM!

2022-09-18 21:50 UTC, merged